- name: Set influx DB repo data
  become: yes
  copy:
    content: 'deb https://repos.influxdata.com/debian {{ raspbian_version }} stable'
    dest: /etc/apt/sources.list.d/influxdb.list

- name: Add InfluxDB repo key
  become: yes
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Update apt
  become: yes
  apt:
    update_cache: yes

- name: Install packages
  become: yes
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ influxdb_packages_pi }}"
  notify: Manage services