- name: Manage services
  become: yes
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: yes
  with_items: "{{ mqtt_services }}"

- name: Start nginx
  become: yes
  service:
    name: start
    state: restarted