- name: Download nodejs repo script
  get_url:
    url: "{{ nodejs.repo[ansible_os_family | lower] }}"
    dest: /tmp/nodejs
    mode: 0755

- name: Execute nodejs repo script
  shell: ./nodejs
  args:
    chdir: /tmp/
  become: yes

- name: Install nodejs
  package: 
    name: nodejs{{ '-' if ansible_os_family | lower == "redhat" else '=' }}{{ nodejs.version }} 
    state: latest
  become: yes
