- name: Create Ansible Folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - /home/{{ ansible_user }}/ansible

- name: Set Ansible Vault Password
  copy:
    content: "{{ ansible.vault.password }}"
    dest: /home/{{ ansible_user }}/ansible/vault-pass-cc

- name: Checkout Otternet Ansible Repo
  git:
    repo: "{{ ansible_deployment_repo }}"
    dest: /home/{{ ansible_user }}/ansible/deployer
    version: "{{ ansible_deployment_branch }}"