ansible_user: "{{ ansible.user.pi }}"
tunnel_ip: "{{ tunnels.sln.hass.ip }}"
raspbian_version: stretch
system_type: pi

tellstick_host: False

ssh_tunnels:
  - type: RemoteForward 
    src: 127.4.1.10:8123 
    dest: localhost:8123
  - type: RemoteForward 
    src: 127.4.1.10:3000
    dest: localhost:3000
  - type: RemoteForward 
    src: 127.4.50.10:8080
    dest: 10.0.1.50:80